baseURL = "https://blog.alejandro9r.xyz"
languageCode = "es-AR"
title = "alejandro9r"
theme = "alejandro9r"
paginate = 3

[markup]
  [markup.highlight]
    style = "monokailight"
  [markup.goldmark.renderer]
    unsafe= true

[params]
  favicon = "/icons/favicon.png"
  mainSections = ["posts", "photos"]
  email = "mail@example.com"
  about = """
[[ BAJO CONSTRUCCIÓN ]]
"""

  [[params.links]]
    [[params.links.link]]
      name = "f"
      href = "/Resume.pdf"
    [[params.links.link]]
      name = "f2"
      href = "/contact"
      smart_email_link = true

  [[params.links]]
    [[params.links.link]]
      name = "Github"
      href = "https://github.com/"
      new_tab = true
    [[params.links.link]]
      name = "Mastodon"
      href = "https://mastodon.social/"
      new_tab = true
    [[params.links.link]]
      name = "Twitter"
      href = "https://twitter.com/"
      new_tab = true
    [[params.links.link]]
      name = "Instagram"
      href = "https://instagram.com/"
      new_tab = true
